#!/bin/sh

set -ev

case "$TEST" in
    none)
        echo Tests skipped! >> "$1"
        ;;
    *)
        echo >> "$1"
        echo Tested on `hostname`. >> "$1"
        echo >> "$1"
        cat /tmp/visual-commit >> "$1"
        ;;
esac
