#!/bin/sh

set -ev

# Make sure we can run git add from out of tree:
export GIT_DIR=`pwd`/.git
export GIT_INDEX_FILE=`pwd`/$GIT_INDEX_FILE
export AM_RUNNING_PRECOMMIT=yes

# Create a clean temp directory for running tests:
TEMPDIR=`mktemp -d -t testing-XXXXXXXXX`
git checkout-index --prefix=$TEMPDIR/ -af
cd $TEMPDIR

case "$TEST" in
    none)
        echo Skipping all tests.
        ;;
    *)
        echo Testing build!
        python hash.py > /tmp/visual-commit
        echo It worked!
        ;;
esac

cd /tmp
rm -rf $TEMPDIR
